name: DVB HB
channelmaps:
    Demo:
        name: HB Demo Channel Map
        provider: DVB
        channels:
            1:
                name: Big Buck Bunny
                source: video/bunny/dash.mpd
            2:
                name: Sintel
                source: video/sintel/dash.mpd
            3:
                name: Cosmic Laundromat
                source: video/cosmic/dash.mpd
            4:
                name: Live
                source: video/live/out.mpd    