name: rai
provider: RAI Italia
providerurl: www.rai.it
frequencies:
  A: 
    tunestring: A
    file: r2.ts
    bitrate: 24882354
    tsid: 2
    onid: 11 
  B: 
    tunestring: B
    port: 5004
  C:
    tunestring: C
    extern:
       command: tsp
       args: -I dvb -a 0 --delivery-system DVB-S2 -f 11766000000 -m 8-PSK -s 29900000 --polarity vertical --satellite-number 1 -P zap RAI1HD



